import Head from "next/head";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Quanta Web</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=""></main>
      <footer className=""></footer>
    </div>
  );
}
